name: Deploy

on:
  push:
    branches: [ "main", "workflow_dispatch"]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: latest

    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm i

    - name: Build
      run: pnpm build

    - name: Configure Cloudflare Page
      run: |
        echo "/*">>./_headers
        echo "  strict-transport-security: max-age=31536000; includeSubDomains; preload">>./_headers

        mv ./_headers ./dist/krtl/

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: "krtl"
        directory: "./dist/krtl/"
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
